### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by mystique09**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
This pull request includes improvements to the README.md file for the ProgPhil Bot project. The changes include:
- A detailed tutorial for the prerequisites and setup instructions for the bot
- Clarification of the instructions for setting up the bot
- Addition of links to relevant resources for contributing and community engagement

Fixes # (issue)
#9 

## Type of change
This pull request includes changes to the documentation and README.md file.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Jedddy — APPROVED** [review]
LGTM 👍

**Review by jovelluna12 — CHANGES_REQUESTED** [review]
please attach this [Dev Guide](https://github.com/ProgrammingPhilippines/progphil-bot/wiki/Development-Guide) made by lead @Jedddy  as it contains more vital information during setting up. best to attach this after number 7 in installation.

sir gerv attached a [template](https://github.com/othneildrew/Best-README-Template) for readmes [here](https://github.com/orgs/ProgrammingPhilippines/projects/2?pane=issue&itemId=8958807) . please refer to it and make changes if necessary.

**Comment by mystique09** [comment]
> please attach this [Dev Guide](https://github.com/ProgrammingPhilippines/progphil-bot/wiki/Development-Guide) made by lead @Jedddy as it contains more vital information during setting up. best to attach this after number 7 in installation.
> 
> sir gerv attached a [template](https://github.com/othneildrew/Best-README-Template) for readmes [here](https://github.com/orgs/ProgrammingPhilippines/projects/2?pane=issue&itemId=8958807) . please refer to it and make changes if necessary.

done

**Review by jovelluna12 — APPROVED** [review]

**Comment by jovelluna12** [comment]
looks good

**Review by Jedddy — DISMISSED** [review]

**Comment by mystique09** [comment]
lmao, sorry may typo eh

**Review by Jedddy — APPROVED** [review]

**Review by vouchard — COMMENTED** [review]
After clone it will not redirect to project directory
add something like "cd to project directory"

**Comment by mystique09** [comment]
> After clone it will not redirect to project directory add something like "cd to project directory"

yeah that make sense

**Review by vouchard — COMMENTED** [review]
Works on my end.

**Review by CunningBard — APPROVED** [review]
LGTM

**Review by vouchard — APPROVED** [review]

**Review by Jedddy — APPROVED** [review]
LGTM

**Review by tora-o — APPROVED** [review]

**Pull request merged**
