### PR TITLE
Multiline with media

### PR DESCRIPTION
**Pull request by tora-o**
# Description

This pull introduces new command `/multi_with_media` 
* accepts an optional argument `photo` 
* the inputs are collected through modal 

#28 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Jedddy — APPROVED** [review]
LGTM👍

**Review by jovelluna12 — DISMISSED** [review]

**Review by CunningBard — APPROVED** [review]
LGTM

**Review by Jedddy — APPROVED** [review]
LgTM

**Review by CunningBard — APPROVED** [review]
LGTM 2.0

**Pull request merged**
